export const GET_POSTS_BY_CATEGORY = 'GET_POSTS_BY_CATEGORY'
export const GET_POSTS = 'GET_POSTS'
export const ADD_POST = 'ADD_POST'
export const FETCH_POST = 'FETCH_POST'
export const VOTE_POST ='VOTE_POST'
export const EDIT_POST = 'EDIT_POST'
export const DELETE_POST = 'DELETE_POST'